### ISSUE TITLE
Bot doesn't load

### ISSUE THREAD

**Issue by Mateocl05** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#169] opened 2020-04-28 01:58 UTC
whwn I open run.bat it's only say 
C:\Users\***\OneDrive\Escritorio\PokeBall-SelfBot-Pokecord-Automation-master>py -3 launcher.py
and it doesn't do anything

**Comment by Hyperclaw79** [comment] 2020-04-28 04:23
This is a duplicate of #158.
Please refer closed issues before opening a new one.

**Closed by Hyperclaw79** 2020-04-28 04:23 UTC
Labels: duplicate, on_ready, wontfix
