### ISSUE TITLE
Stuck at command

### ISSUE THREAD

**Issue by karmahakase** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#178] opened 2020-05-24 21:09 UTC
# Title: [] Not doing anything

# Body:

## Problem:
When I launch the run.bat I just get a screen without anything but the command, but the
underscore is blinking.

## config.json:
only edited the token to my self-token.

## Traceback and Screenshots:
![image](https://user-images.githubusercontent.com/37049666/82765019-8e77bb00-9e13-11ea-932e-4719af437c2f.png)

## Specs.
**Win10**:
**Latest**:
**3.7.7**:

**Comment by Hyperclaw79** [comment] 2020-05-25 05:20
This is a duplicate of #158.
Please refer closed issues before opening a new one.

**Closed by Hyperclaw79** 2020-05-25 05:20 UTC
