### ISSUE TITLE
Invalid token

### ISSUE THREAD

**Issue by DynamoYT** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#196] opened 2020-09-27 08:46 UTC
```Traceback (most recent call last):
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 288, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "launcher.py", line 19, in <module>
    bot.run()
  File "C:\Users\verma\Desktop\html\PokeBall-SelfBot-Pokecord-Automation\pokeball.py", line 51, in run
    super().run(self.configs['token'], bot=False)
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 678, in run
    return future.result()
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 658, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 621, in start
    await self.login(*args, bot=bot)
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\client.py", line 472, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\http.py", line 292, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000014D86A0C430>
Traceback (most recent call last):
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\verma\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed````

**Comment by Hyperclaw79** [comment] 2020-09-27 09:13
Duplicate of #84, #120, etc.

**Closed** 2020-09-27 09:13 UTC
Labels: duplicate, local
