### ISSUE TITLE
Improper token

### ISSUE THREAD

**Issue by Prateekkota** [Hyperclaw79/PokeBall-SelfBot-Pokecord-Automation#204] opened 2020-11-20 14:19 UTC
I am getting these issues while I run run.bat

C:\Users\Aaron\Desktop\PokeBall-SelfBot-Pokecord-Automation-master>py -3 launcher.py
Traceback (most recent call last):
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 291, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Aaron\Desktop\PokeBall-SelfBot-Pokecord-Automation-master\launcher.py", line 19, in <module>
    bot.run()
  File "C:\Users\Aaron\Desktop\PokeBall-SelfBot-Pokecord-Automation-master\pokeball.py", line 51, in run
    super().run(self.configs['token'], bot=False)
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 708, in run
    return future.result()
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 687, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 650, in start
    await self.login(*args, bot=bot)
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\client.py", line 499, in login
    await self.http.static_login(token.strip(), bot=bot)
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\http.py", line 295, in static_login
    raise LoginFailure('Improper token has been passed.') from exc
discord.errors.LoginFailure: Improper token has been passed.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002B7561E84C0>
Traceback (most recent call last):
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\Aaron\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

C:\Users\Aaron\Desktop\PokeBall-SelfBot-Pokecord-Automation-master>timeout -1

Press any key to continue ...

**Comment by Hyperclaw79** [comment] 2020-11-20 14:28
Duplicate of #84.

**Closed** 2020-11-20 14:28 UTC
Labels: duplicate
